/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package otus.qa.kotlin.hw

import TestRunnerImpl

class WebPageSteps {
    fun beforeAll() {
        println("#beforeAll")
    }

    fun beforeEach() {
        println("#beforeEach")
    }

    fun some1Test() {
        println("#some1Test")
    }

    fun some2Test() {
        println("#some2Test")
    }

    fun afterEach() {
        println("#afterEach")
    }

    fun afterAll() {
        println("#afterAll")
    }
}

fun main() {
    TestRunnerImpl().runTest(WebPageSteps()) { WebPageSteps().some2Test() }
}
