/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package otus.qa.kotlin.hw

import kotlin.test.Test
import kotlin.test.assertNotNull

class WebPageStepsTest {
    @Test fun appHasAGreetingTest() {
        val classUnderTest = WebPageSteps()
        assertNotNull(classUnderTest.afterAll(), "app should have a call")
    }
}
